#!/bin/python
# Obfuscated by @CesarHackGray
# Los creditos son para @Cesar
# Contactame https://t.me/CesarGray
# https://www.youtube.com/channel/UCjs0N8PbEo-se0r_4O_svNQ
#
import base64
Cesar = """IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCmltcG9ydCBvcwpmcm9tIHRpbWUgaW1wb3J0IHNsZWVwCmEg PSdcMDMzWzkybScKYiA9J1wwMzNbOTFtJwpjID0nXDAzM1swbScKRCA9ICdcMDMzWzk2bScKb3Mu c3lzdGVtKCdjbGVhcicpCnByaW50KGErJ1x0ICBUZXJtdXggVGVjbGFzIGFkaWNpb25hbGVzICcp CnByaW50KGErJysnKjQwKQpwcmludCgnXG5Qcm9zZXMuLicpCnNsZWVwKDEpCnByaW50KGIrJ1xu WyFdIFJlY3VwZXJhciBlbCBhcmNoaXZvIHByZWRldGVybWluYWRvIGRlIFRlcm11eCAnKQpzbGVl cCgxKQp0cnk6CiAgICAgIG9zLm1rZGlyKCcvZGF0YS9kYXRhL2NvbS50ZXJtdXgvZmlsZXMvaG9t ZS8udGVybXV4JykKZXhjZXB0OgogICAgICBwYXNzCnByaW50KGErJ1shXcKhw4l4aXRvISAnKQpz bGVlcCgxKQpwcmludChiKydcblshXSBhZ3JlZ2FuZG8gYm90b25lcyAgZW4gc3UgdGVjbGFkbyBw cmVkZXRlcm1pbmFkbyAuLi4gJykKc2xlZXAoMSkKCmtleSA9ICJleHRyYS1rZXlzID0gW1snRVND JywnLycsJy0nLCdIT01FJywnVVAnLCdFTkQnLCdQR1VQJ10sWydUQUInLCdDVFJMJywnQUxUJywn TEVGVCcsJ0RPV04nLCdSSUdIVCcsJ1BHRE4nXV0iCmtvbnRvbCA9IG9wZW4oJy9kYXRhL2RhdGEv Y29tLnRlcm11eC9maWxlcy9ob21lLy50ZXJtdXgvdGVybXV4LnByb3BlcnRpZXMnLCd3JykKa29u dG9sLndyaXRlKGtleSkKa29udG9sLmNsb3NlKCkKc2xlZXAoMSkKcHJpbnQoYSsnWyFdIFByb2Nl c2FuZG8gICEnKQpzbGVlcCgxKQpwcmludChiKydcblshXSBFc3BlcmEgdW4gc2VndW5kbyAnKQpz bGVlcCg0KQpvcy5zeXN0ZW0oJ3Rlcm11eC1yZWxvYWQtc2V0dGluZ3MnKQpwcmludChhKydbIV0g UHJvY2VzbyBjb21wbGV0byAhISAnKQpwcmludChhKycrJyo0MCkKcHJpbnQoRCsnWyFdwqEgUE9S OiBKT1JHRSBCQVJCQSEgJykKCiMK"""
eval(compile(base64.b64decode(Cesar),'','exec'))
